# Generated by Django 4.2.7 on 2024-01-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.ImageField(upload_to='myapp/uploads')),
                ('title', models.CharField(max_length=600)),
                ('description', models.TextField(max_length=600)),
                ('technology', models.ImageField(upload_to='myapp/technologies')),
            ],
        ),
    ]
