# Generated by Django 4.2.7 on 2024-01-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.FileField(blank=True, upload_to='myapp/technologies'),
        ),
    ]
