# Generated by Django 4.2.7 on 2024-01-12 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_imageurl_alter_project_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
        migrations.CreateModel(
            name='TechnologyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_image', models.ImageField(upload_to='technology_images')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_images', to='projects.project')),
            ],
        ),
    ]
