# Generated by Django 4.2.7 on 2024-01-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_imageurl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechnologyImages',
            new_name='TechnologyImage',
        ),
    ]
