# Generated by Django 4.2.7 on 2024-01-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_technologyimages_technologyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('accomplishments', models.CharField(max_length=200)),
                ('contact_information', models.CharField(max_length=200)),
            ],
        ),
    ]
