# Generated by Django 4.2.7 on 2024-01-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_aboutme_accomplishments_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMe',
        ),
    ]
