# Generated by Django 4.2.7 on 2024-01-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_delete_aboutme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInformation',
        ),
    ]
